[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
x402_hack_payment = "339A4zncMj8fbM2zvEopYXu6TZqRieJKebDiXCKwquA5"

[programs.devnet]
x402_hack_payment = "339A4zncMj8fbM2zvEopYXu6TZqRieJKebDiXCKwquA5"
delegation_program = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
permission_program = "ACLseoPoyC3cBqoUtkbjZ4aDrkurZW86v19pXz2XQnp1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./phantom-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
